services:
  web:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - ./:/app:cached
    environment:
      - NODE_ENV=development
    command: npx nodemon index.js
  proxy:
    image: nginx:stable-alpine
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
